'''
    Module:
        Command-line arguments to the plotting applications.
'''
import argparse
from module_utility import str2bool, strs2bool

## Get command-line arguments
def getarg(parser, program):

    # dimension
    if program == 'graph':
        parser.add_argument('-n1', '--n1', type=str, help='number of samples along axis 1; accepts a list for multi-file inputs', nargs='+', default=None)
    else:
        parser.add_argument('-n1', '--n1', type=int, help='number of grid points along axis 1 (rows)', default=None)
    parser.add_argument('-n2', '--n2', type=int, help='number of grid points along axis 2 (columns)', default=None)
    parser.add_argument('-n3', '--n3', type=int, help='number of grid points along axis 3 (depth)', default=None)
    parser.add_argument('-o1', '--o1', type=str, help='coordinate origin of axis 1 (default: 0.0)', default='0.0')
    parser.add_argument('-o2', '--o2', type=str, help='coordinate origin of axis 2 (default: 0.0)', default='0.0')
    parser.add_argument('-o3', '--o3', type=str, help='coordinate origin of axis 3 (default: 0.0)', default='0.0')
    parser.add_argument('-d1', '--d1', type=str, help='grid spacing along axis 1; sets the coordinate scale (default: 1.0)', default='1.0')
    parser.add_argument('-d2', '--d2', type=str, help='grid spacing along axis 2; sets the coordinate scale (default: 1.0)', default='1.0')
    parser.add_argument('-d3', '--d3', type=str, help='grid spacing along axis 3; sets the coordinate scale (default: 1.0)', default='1.0')

    # io
    parser.add_argument('-in', '--infile', type=str, help='input file path(s); multiple files are concatenated along axis 2', nargs='+', default=None)
    parser.add_argument('-out', '--outfile', type=str, help='output file path(s); supported: .pdf .png .jpg .eps .ps .tiff; omit to display on screen', nargs='+', default=None)
    parser.add_argument('-background', '--background', type=str, help='path to a second data file rendered as a semi-transparent background image', default=None)
    parser.add_argument('-mask', '--mask', type=str, help='path to a binary mask file; zero values suppress data at those locations', default=None)
    parser.add_argument('-dtype', '--datatype', type=str, help='numeric type of the binary input: float (32-bit), double (64-bit), int (16-bit) (default: float)', default='float')
    parser.add_argument('-endian', '--endian', type=str, help='byte order of the binary input: little or big (default: little)', default='little')
    parser.add_argument('-transpose', '--transpose', type=str2bool, help='transpose the stored array (swap axis 1 and axis 2) before plotting (y/n)', default='n')
    parser.add_argument('-dpi', '--dpi', type=str, help='output image resolution in dots per inch (default: 300)', default='300')

    # processing
    parser.add_argument('-norm', '--norm', type=str, help='color scaling: linear (default) or log (applies log10 to data before colormapping)', default='linear')
    parser.add_argument('-base', '--base', type=str, help='logarithm base when norm=log (default: 10)', default='10')
    parser.add_argument('-flip1', '--flip1', type=str2bool, help='reverse the data array along axis 1 before plotting (y/n)', default='n')
    parser.add_argument('-flip2', '--flip2', type=str2bool, help='reverse the data array along axis 2 before plotting (y/n)', default='n')
    parser.add_argument('-flip3', '--flip3', type=str2bool, help='reverse the data array along axis 3 before plotting (y/n)', default='n')

    # axis
    parser.add_argument('-reverse1', '--reverse1', type=str2bool, help='invert the axis-1 direction on the plot (y/n)', default='n')
    parser.add_argument('-reverse2', '--reverse2', type=str2bool, help='invert the axis-2 direction on the plot (y/n)', default='n')
    parser.add_argument('-reverse3', '--reverse3', type=str2bool, help='invert the axis-3 direction on the plot (y/n)', default='n')
    parser.add_argument('-norm1', '--norm1', type=str, help='axis-1 tick spacing: linear (default) or log', default='linear')
    parser.add_argument('-norm2', '--norm2', type=str, help='axis-2 tick spacing: linear (default) or log', default='linear')
    parser.add_argument('-norm3', '--norm3', type=str, help='axis-3 tick spacing: linear (default) or log', default='linear')
    parser.add_argument('-base1', '--base1', type=str, help='logarithm base for axis-1 tick labels when norm1=log (default: 10)', default='10')
    parser.add_argument('-base2', '--base2', type=str, help='logarithm base for axis-2 tick labels when norm2=log (default: 10)', default='10')
    parser.add_argument('-base3', '--base3', type=str, help='logarithm base for axis-3 tick labels when norm3=log (default: 10)', default='10')
    parser.add_argument('-label1', '--label1', type=str, help='axis-1 label text (default: "Axis 1")', default='Axis 1')
    parser.add_argument('-label2', '--label2', type=str, help='axis-2 label text (default: "Axis 2")', default='Axis 2')
    parser.add_argument('-label3', '--label3', type=str, help='axis-3 label text (default: "Axis 3")', default='Axis 3')
    parser.add_argument('-label1pad', '--label1pad', type=str, help='extra padding between axis-1 label and tick labels, in figure fraction (default: 0.075)', default='0.075')
    parser.add_argument('-label2pad', '--label2pad', type=str, help='extra padding between axis-2 label and tick labels, in figure fraction (default: 0.075)', default='0.075')
    parser.add_argument('-label3pad', '--label3pad', type=str, help='extra padding between axis-3 label and tick labels, in figure fraction (default: 0.075)', default='0.075')
    parser.add_argument('-label1size', '--label1size', type=str, help='font size of axis-1 label in points (default: 16)', default='16.0')
    parser.add_argument('-label2size', '--label2size', type=str, help='font size of axis-2 label in points (default: 16)', default='16.0')
    parser.add_argument('-label3size', '--label3size', type=str, help='font size of axis-3 label in points (default: 16)', default='16.0')
    parser.add_argument('-label1loc', '--label1loc', type=str, help='axis-1 label anchor: center, left, right, or a float in [0, 1]', default=None)
    parser.add_argument('-label2loc', '--label2loc', type=str, help='axis-2 label anchor: center, left, right, or a float in [0, 1]', default=None)
    parser.add_argument('-label3loc', '--label3loc', type=str, help='axis-3 label anchor: center, left, right, or a float in [0, 1]', default=None)
    parser.add_argument('-x1beg', '--x1beg', type=str, help='crop axis 1 to start at this real-coordinate value', default=None)
    parser.add_argument('-x1end', '--x1end', type=str, help='crop axis 1 to end at this real-coordinate value', default=None)
    parser.add_argument('-x2beg', '--x2beg', type=str, help='crop axis 2 to start at this real-coordinate value', default=None)
    parser.add_argument('-x2end', '--x2end', type=str, help='crop axis 2 to end at this real-coordinate value', default=None)
    parser.add_argument('-x3beg', '--x3beg', type=str, help='crop axis 3 to start at this real-coordinate value', default=None)
    parser.add_argument('-x3end', '--x3end', type=str, help='crop axis 3 to end at this real-coordinate value', default=None)
    parser.add_argument('-hideticks', '--hideticks', type=str2bool, help='hide all tick marks and tick labels (y/n)', default='n')
    parser.add_argument('-ticks1', '--ticks1', type=str, help='override axis-1 ticks as comma-separated pos:label pairs, e.g. 0.5:A,1.0:B', nargs='+', default=None)
    parser.add_argument('-ticks2', '--ticks2', type=str, help='override axis-2 ticks as comma-separated pos:label pairs, e.g. 0.5:A,1.0:B', nargs='+', default=None)
    parser.add_argument('-ticks3', '--ticks3', type=str, help='override axis-3 ticks as comma-separated pos:label pairs, e.g. 0.5:A,1.0:B', nargs='+', default=None)
    parser.add_argument('-tick1beg', '--tick1beg', type=str, help='value of the first major tick along axis 1', default=None)
    parser.add_argument('-tick2beg', '--tick2beg', type=str, help='value of the first major tick along axis 2', default=None)
    parser.add_argument('-tick3beg', '--tick3beg', type=str, help='value of the first major tick along axis 3', default=None)
    parser.add_argument('-tick1end', '--tick1end', type=str, help='value of the last major tick along axis 1', default=None)
    parser.add_argument('-tick2end', '--tick2end', type=str, help='value of the last major tick along axis 2', default=None)
    parser.add_argument('-tick3end', '--tick3end', type=str, help='value of the last major tick along axis 3', default=None)
    parser.add_argument('-tick1d', '--tick1d', type=str, help='interval between major ticks along axis 1 (auto if omitted)', default=None)
    parser.add_argument('-tick2d', '--tick2d', type=str, help='interval between major ticks along axis 2 (auto if omitted)', default=None)
    parser.add_argument('-tick3d', '--tick3d', type=str, help='interval between major ticks along axis 3 (auto if omitted)', default=None)
    parser.add_argument('-mtick1', '--mtick1', type=int, help='number of minor ticks between consecutive major ticks along axis 1 (default: 0)', default=0)
    parser.add_argument('-mtick2', '--mtick2', type=int, help='number of minor ticks between consecutive major ticks along axis 2 (default: 0)', default=0)
    parser.add_argument('-mtick3', '--mtick3', type=int, help='number of minor ticks between consecutive major ticks along axis 3 (default: 0)', default=0)
    parser.add_argument('-tick1size', '--tick1size', type=str, help='font size of axis-1 tick labels in points (inherits label1size if omitted)', default=None)
    parser.add_argument('-tick2size', '--tick2size', type=str, help='font size of axis-2 tick labels in points (inherits label2size if omitted)', default=None)
    parser.add_argument('-tick3size', '--tick3size', type=str, help='font size of axis-3 tick labels in points (inherits label3size if omitted)', default=None)
    parser.add_argument('-tickmajorlen', '--tickmajorlen', type=str, help='length of major tick marks in points (default: 5.0)', default='5.0')
    parser.add_argument('-tickminorlen', '--tickminorlen', type=str, help='length of minor tick marks in points (defaults to half of tickmajorlen)', default=None)
    parser.add_argument('-tickmajorwid', '--tickmajorwid', type=str, help='line width of major tick marks in points (default: 1.0)', default='1.0')
    parser.add_argument('-tickminorwid', '--tickminorwid', type=str, help='line width of minor tick marks in points (defaults to tickmajorwid)', default=None)
    parser.add_argument('-tick1format', '--tick1format', type=str, help='number format for axis-1 tick labels: sci (scientific notation) or plain (default: sci)', default='sci')
    parser.add_argument('-tick2format', '--tick2format', type=str, help='number format for axis-2 tick labels: sci (scientific notation) or plain (default: sci)', default='sci')
    parser.add_argument('-tick3format', '--tick3format', type=str, help='number format for axis-3 tick labels: sci (scientific notation) or plain (default: sci)', default='sci')
    parser.add_argument('-tick1rot', '--tick1rot', type=str, help='rotation of axis-1 tick labels in degrees (default: 0)', default='0.0')
    parser.add_argument('-tick2rot', '--tick2rot', type=str, help='rotation of axis-2 tick labels in degrees (default: 0)', default='0.0')
    parser.add_argument('-tick3rot', '--tick3rot', type=str, help='rotation of axis-3 tick labels in degrees (default: 0)', default='0.0')
    parser.add_argument('-tick1label', '--tick1label', type=str2bool, help='show (y) or hide (n) axis-1 tick labels', default='y')
    parser.add_argument('-tick2label', '--tick2label', type=str2bool, help='show (y) or hide (n) axis-2 tick labels', default='y')
    parser.add_argument('-tick3label', '--tick3label', type=str2bool, help='show (y) or hide (n) axis-3 tick labels', default='y')
    parser.add_argument('-frameleft', '--frameleft', type=str2bool, help='show (y) or hide (n) the left frame edge', default='y')
    parser.add_argument('-frameright', '--frameright', type=str2bool, help='show (y) or hide (n) the right frame edge', default='y')
    parser.add_argument('-frametop', '--frametop', type=str2bool, help='show (y) or hide (n) the top frame edge', default='y')
    parser.add_argument('-framebottom', '--framebottom', type=str2bool, help='show (y) or hide (n) the bottom frame edge', default='y')
    parser.add_argument('-tickleft', '--tickleft', type=str2bool, help='show (y) or hide (n) tick marks on the left frame edge', default='y')
    parser.add_argument('-tickright', '--tickright', type=str2bool, help='show (y) or hide (n) tick marks on the right frame edge', default='n')
    if program == 'graph':
        parser.add_argument('-ticktop', '--ticktop', type=str2bool, help='show (y) or hide (n) tick marks on the top frame edge', default='n')
        parser.add_argument('-tickbottom', '--tickbottom', type=str2bool, help='show (y) or hide (n) tick marks on the bottom frame edge', default='y')
    else:
        parser.add_argument('-ticktop', '--ticktop', type=str2bool, help='show (y) or hide (n) tick marks on the top frame edge', default='y')
        parser.add_argument('-tickbottom', '--tickbottom', type=str2bool, help='show (y) or hide (n) tick marks on the bottom frame edge', default='n')

    # color
    parser.add_argument('-ncolor', '--ncolor', type=int, help='number of discrete color levels in the colormap (default: 256)', default=256)
    parser.add_argument('-color', '--colormap', type=str, help='matplotlib colormap name, e.g. gray, jet, seismic, viridis, RdBu (default: depends on program)', default=None)
    parser.add_argument('-cscale', '--colorscale', type=str, help='multiply all data values by this factor before colormapping', default=None)
    parser.add_argument('-clip', '--clip', type=str, help='symmetric amplitude clip: values outside [-clip, +clip] are clamped to the color range limits', default=None)
    parser.add_argument('-cmin', '--cmin', type=str, help='explicit lower bound of the color scale (overrides clip and cperc)', default=None)
    parser.add_argument('-cmax', '--cmax', type=str, help='explicit upper bound of the color scale (overrides clip and cperc)', default=None)
    parser.add_argument('-cperc', '--cperc', type=str, help='use the central N%% of the data range for colormapping, e.g. 98 clips the top and bottom 1%% (default: 100)', default='100.0')
    parser.add_argument('-alphas', '--alphas', type=str, help='transparency control as value:alpha pairs, e.g. 0.0:0.0,1.0:1.0; values between pairs are interpolated', default=None)
    parser.add_argument('-ctruncbeg', '--ctruncbeg', type=str, help='trim the low end of the colormap; 0.0=keep all, 0.1=drop bottom 10%% (default: 0.0)', default='0.0')
    parser.add_argument('-ctruncend', '--ctruncend', type=str, help='trim the high end of the colormap; 1.0=keep all, 0.9=drop top 10%% (default: 1.0)', default='1.0')
    parser.add_argument('-backcolor', '--backcolormap', type=str, help='colormap for the background image (default: hsv)', default='hsv')
    parser.add_argument('-backcscale', '--backcolorscale', type=str, help='multiply background data values by this factor before colormapping', default=None)
    parser.add_argument('-backclip', '--backclip', type=str, help='symmetric clip for the background image: values outside [-backclip, +backclip] are clamped', default=None)
    parser.add_argument('-backcmin', '--backcmin', type=str, help='explicit lower bound of the background color scale', default=None)
    parser.add_argument('-backcmax', '--backcmax', type=str, help='explicit upper bound of the background color scale', default=None)
    parser.add_argument('-backcperc', '--backcperc', type=str, help='percentile clip for the background image (default: 100)', default='100.0')
    parser.add_argument('-backalphas', '--backalphas', type=str, help='transparency map for the background image as value:alpha pairs', default=None)
    parser.add_argument('-backctruncbeg', '--backctruncbeg', type=str, help='trim the low end of the background colormap (default: 0.0)', default='0.0')
    parser.add_argument('-backctruncend', '--backctruncend', type=str, help='trim the high end of the background colormap (default: 1.0)', default='1.0')
    parser.add_argument('-shading', '--shading', type=str, help='hillshade blending mode overlaid on the image: overlay, soft, hsv, or pegtop', default=None)
    parser.add_argument('-shading_scale', '--shading_scale', type=float, help='vertical exaggeration factor for hillshade relief (default: 1.0)', default=1.0)
    parser.add_argument('-shading_angle', '--shading_angle', type=str, help='hillshade light direction as "azimuth,altitude" in degrees (default: 180,45)', default='180,45')

    # colorbar
    parser.add_argument('-legend', '--legend', type=str2bool, help='attach an inline colorbar to the plot (y/n)', default='n')
    parser.add_argument('-backlegend', '--backlegend', type=str2bool, help='attach an inline colorbar for the background image (y/n)', default='n')
    parser.add_argument('-lloc', '--lloc', type=str, help='colorbar position: right (default), left, top, or bottom', default='right')
    parser.add_argument('-lpad', '--lpad', type=str, help='gap between the plot area and the colorbar in inches', default=None)
    parser.add_argument('-lheight', '--lheight', type=str, help='colorbar height in inches (auto if omitted)', default=None)
    parser.add_argument('-lwidth', '--lwidth', type=str, help='colorbar width in inches (auto if omitted)', default=None)
    parser.add_argument('-ld', '--ld', type=str, help='interval between major colorbar tick marks (auto if omitted)', default=None)
    parser.add_argument('-ltickbeg', '--ltickbeg', type=str, help='value of the first major colorbar tick (auto if omitted)', default=None)
    parser.add_argument('-ltickend', '--ltickend', type=str, help='value of the last major colorbar tick (auto if omitted)', default=None)
    parser.add_argument('-lticksize', '--lticksize', type=str, help='font size of colorbar tick labels in points (inherits unitsize if omitted)', default=None)
    parser.add_argument('-lmtick', '--lmtick', type=int, help='number of minor ticks between consecutive major colorbar ticks (default: 0)', default=0)
    parser.add_argument('-lreverse', '--lreverse', type=str2bool, help='reverse the colorbar direction (y/n)', default='n')
    parser.add_argument('-unit', '--unit', type=str, help='colorbar label / physical unit string, e.g. "m/s" or "km"', default=None)
    parser.add_argument('-unitsize', '--unitsize', type=str, help='font size of the colorbar unit label in points', default=None)
    parser.add_argument('-unitpad', '--unitpad', type=str, help='padding between the colorbar unit label and tick labels in points', default=None)

    # grid
    parser.add_argument('-grid1', '--grid1', type=str2bool, help='draw major grid lines perpendicular to axis 1 (y/n)', default='n')
    parser.add_argument('-grid2', '--grid2', type=str2bool, help='draw major grid lines perpendicular to axis 2 (y/n)', default='n')
    parser.add_argument('-grid3', '--grid3', type=str2bool, help='draw major grid lines perpendicular to axis 3 (y/n)', default='n')
    parser.add_argument('-grid1width', '--grid1width', type=str, help='line width of major grid lines perpendicular to axis 1', default=None)
    parser.add_argument('-grid2width', '--grid2width', type=str, help='line width of major grid lines perpendicular to axis 2', default=None)
    parser.add_argument('-grid3width', '--grid3width', type=str, help='line width of major grid lines perpendicular to axis 3', default=None)
    parser.add_argument('-grid1color', '--grid1color', type=str, help='color of major grid lines perpendicular to axis 1 (default: gray)', default='gray')
    parser.add_argument('-grid2color', '--grid2color', type=str, help='color of major grid lines perpendicular to axis 2 (default: gray)', default='gray')
    parser.add_argument('-grid3color', '--grid3color', type=str, help='color of major grid lines perpendicular to axis 3 (default: gray)', default='gray')
    parser.add_argument('-grid1style', '--grid1style', type=str, help='line style of major grid lines perpendicular to axis 1: - -- : -. (default: --)', default='--')
    parser.add_argument('-grid2style', '--grid2style', type=str, help='line style of major grid lines perpendicular to axis 2: - -- : -. (default: --)', default='--')
    parser.add_argument('-grid3style', '--grid3style', type=str, help='line style of major grid lines perpendicular to axis 3: - -- : -. (default: --)', default='--')
    parser.add_argument('-mgrid1', '--mgrid1', type=str2bool, help='draw minor grid lines perpendicular to axis 1 (y/n)', default='n')
    parser.add_argument('-mgrid2', '--mgrid2', type=str2bool, help='draw minor grid lines perpendicular to axis 2 (y/n)', default='n')
    parser.add_argument('-mgrid3', '--mgrid3', type=str2bool, help='draw minor grid lines perpendicular to axis 3 (y/n)', default='n')
    parser.add_argument('-mgrid1width', '--mgrid1width', type=str, help='line width of minor grid lines perpendicular to axis 1', default=None)
    parser.add_argument('-mgrid2width', '--mgrid2width', type=str, help='line width of minor grid lines perpendicular to axis 2', default=None)
    parser.add_argument('-mgrid3width', '--mgrid3width', type=str, help='line width of minor grid lines perpendicular to axis 3', default=None)
    parser.add_argument('-mgrid1color', '--mgrid1color', type=str, help='color of minor grid lines perpendicular to axis 1 (default: k)', default='k')
    parser.add_argument('-mgrid2color', '--mgrid2color', type=str, help='color of minor grid lines perpendicular to axis 2 (default: k)', default='k')
    parser.add_argument('-mgrid3color', '--mgrid3color', type=str, help='color of minor grid lines perpendicular to axis 3 (default: k)', default='k')
    parser.add_argument('-mgrid1style', '--mgrid1style', type=str, help='line style of minor grid lines perpendicular to axis 1: - -- : -. (default: :)', default=':')
    parser.add_argument('-mgrid2style', '--mgrid2style', type=str, help='line style of minor grid lines perpendicular to axis 2: - -- : -. (default: :)', default=':')
    parser.add_argument('-mgrid3style', '--mgrid3style', type=str, help='line style of minor grid lines perpendicular to axis 3: - -- : -. (default: :)', default=':')

    # title
    parser.add_argument('-title', '--title', type=str, help='plot title text', default=None)
    parser.add_argument('-titlesize', '--titlesize', type=str, help='title font size in points (inherits label1size if omitted)', default=None)
    parser.add_argument('-titlex', '--titlex', type=str, help='title horizontal position as axes fraction, 0=left 1=right (default: 0.5)', default='0.50')
    parser.add_argument('-titley', '--titley', type=str, help='title vertical position as axes fraction, 1.0=top edge (default: 1.25)', default='1.25')

    # volume
    if program in ['volume', 'volcon']:
        parser.add_argument('-axis1loc', '--axis1loc', type=str, help='side that axis-1 ticks and label appear on: left (default) or right', default='left')
        parser.add_argument('-axis2loc', '--axis2loc', type=str, help='side that axis-2 ticks and label appear on: top (default) or bottom', default='top')
        parser.add_argument('-axis3loc', '--axis3loc', type=str, help='side that axis-3 ticks and label appear on: top (default) or bottom', default='top')
        parser.add_argument('-angle', '--angle', type=str, help='isometric view angles as "azimuth,elevation" in [0, 90] degrees', nargs='+', default=None)
        parser.add_argument('-octant', '--octant', type=str, help='visible octant of the 3-D volume: sign combination of axis directions, e.g. --+ (default)', default='--+')
        parser.add_argument('-centerframe', '--centerframe', type=str2bool, help='draw frame lines at the slice intersection planes (y/n)', default='y')
        parser.add_argument('-pvopacity', '--pvopacity', type=str, help='opacity transfer function for pyvista 3D rendering: uniform (default, fully opaque), sigmoid, linear, geom, etc.', default='uniform')
        parser.add_argument('-pvticks', '--pvticks', type=str2bool, help='show axis ticks and labels in pyvista 3D rendering (default: y)', default='y')

    # slice
    if program in ['volume', 'volcon', 'slice', 'slicon']:
        parser.add_argument('-slice1', '--slice1', type=str, help='position of the axis-1 slice in real coordinates (default: mid-point)', default=None)
        parser.add_argument('-slice2', '--slice2', type=str, help='position of the axis-2 slice in real coordinates (default: mid-point)', default=None)
        parser.add_argument('-slice3', '--slice3', type=str, help='position of the axis-3 slice in real coordinates (default: mid-point)', default=None)
    if program in ['slice', 'slicon']:
        parser.add_argument('-slicegap', '--slicegap', type=str, help='white space between the three orthogonal slice panels in inches (default: 0.1)', default='0.1')
        parser.add_argument('-sliceline1', '--sliceline1', type=str2bool, help='draw a line marking the axis-1 slice position on the other two panels (y/n)', default='y')
        parser.add_argument('-sliceline2', '--sliceline2', type=str2bool, help='draw a line marking the axis-2 slice position on the other two panels (y/n)', default='y')
        parser.add_argument('-sliceline3', '--sliceline3', type=str2bool, help='draw a line marking the axis-3 slice position on the other two panels (y/n)', default='y')
        parser.add_argument('-sliceline1width', '--sliceline1width', type=str, help='line width of the axis-1 slice marker (default: 1.0)', default='1.0')
        parser.add_argument('-sliceline2width', '--sliceline2width', type=str, help='line width of the axis-2 slice marker (default: 1.0)', default='1.0')
        parser.add_argument('-sliceline3width', '--sliceline3width', type=str, help='line width of the axis-3 slice marker (default: 1.0)', default='1.0')
        parser.add_argument('-sliceline1color', '--sliceline1color', type=str, help='color of the axis-1 slice marker (default: k)', default='k')
        parser.add_argument('-sliceline2color', '--sliceline2color', type=str, help='color of the axis-2 slice marker (default: k)', default='k')
        parser.add_argument('-sliceline3color', '--sliceline3color', type=str, help='color of the axis-3 slice marker (default: k)', default='k')
        parser.add_argument('-sliceline1style', '--sliceline1style', type=str, help='line style of the axis-1 slice marker: - -- : -. (default: -)', default='-')
        parser.add_argument('-sliceline2style', '--sliceline2style', type=str, help='line style of the axis-2 slice marker: - -- : -. (default: -)', default='-')
        parser.add_argument('-sliceline3style', '--sliceline3style', type=str, help='line style of the axis-3 slice marker: - -- : -. (default: -)', default='-')

    # annotations
    parser.add_argument('-curve', '--curve', type=str, help='path(s) to ASCII curve files; columns are x1,x2 (line) or x1,x2,value (scatter)', nargs='+', default=None)
    parser.add_argument('-curvestyle', '--curvestyle', type=str, help='line/scatter style per curve file: - solid, -- dashed, : dotted, o/s/^ scatter markers', nargs='+', default=None)
    parser.add_argument('-curvesize', '--curvesize', type=str, help='scatter marker size per curve file in points', nargs='+', default=None)
    parser.add_argument('-curveselect', '--curveselect', type=str, help='column indices to read from each curve file (0-based), e.g. 0,2 reads columns 0 and 2', nargs='+', default=None)
    parser.add_argument('-curvewidth', '--curvewidth', type=str, help='line width per curve file in points', nargs='+', default=None)
    parser.add_argument('-curvecolor', '--curvecolor', type=str, help='line or marker color per curve file', nargs='+', default=None)
    parser.add_argument('-curvefacecolor', '--curvefacecolor', type=str, help='marker face color per curve file', nargs='+', default=None)
    parser.add_argument('-curveedgecolor', '--curveedgecolor', type=str, help='marker edge color per curve file', nargs='+', default=None)
    parser.add_argument('-curveorder', '--curveorder', type=str, help='z-order per curve (higher value appears in front)', nargs='+', default=None)
    parser.add_argument('-text', '--text', type=str, help='text annotation string(s)', nargs='+', default=None)
    parser.add_argument('-textstyle', '--textstyle', type=str, help='font style per annotation: normal, italic, or bold', nargs='+', default=None)
    parser.add_argument('-textloc', '--textloc', type=str, help='position of each text annotation as "x1,x2" in real axis coordinates', nargs='+', default=None)
    parser.add_argument('-textrotation', '--textrotation', type=str, help='rotation of each text annotation in degrees', nargs='+', default=None)
    parser.add_argument('-textsize', '--textsize', type=str, help='font size of each text annotation in points', nargs='+', default=None)
    parser.add_argument('-textcolor', '--textcolor', type=str, help='color of each text annotation', nargs='+', default=None)
    parser.add_argument('-textbox', '--textbox', type=str, help='draw a bounding box around each annotation (y/n)', nargs='+', default=None)
    parser.add_argument('-textboxedgecolor', '--textboxedgecolor', type=str, help='bounding box edge color per annotation', nargs='+', default=None)
    parser.add_argument('-textboxfacecolor', '--textboxfacecolor', type=str, help='bounding box fill color per annotation', nargs='+', default=None)
    parser.add_argument('-textboxalpha', '--textboxalpha', type=str, help='bounding box transparency per annotation (0=transparent, 1=opaque)', nargs='+', default=None)
    parser.add_argument('-textboxpad', '--textboxpad', type=str, help='padding inside the bounding box in points per annotation', nargs='+', default=None)
    parser.add_argument('-textboxstyle', '--textboxstyle', type=str, help='bounding box shape per annotation: square, round, round4, or sawtooth', nargs='+', default=None)
    parser.add_argument('-textorder', '--textorder', type=str, help='z-order per text annotation (higher value appears in front)', nargs='+', default=None)
    parser.add_argument('-arrow', '--arrow', type=str, help='arrow specification as "x1start,x2start,x1end,x2end" in real coordinates', nargs='+', default=None)
    parser.add_argument('-arrowfacecolor', '--arrowfacecolor', type=str, help='arrow head fill color per arrow', nargs='+', default=None)
    parser.add_argument('-arrowedgecolor', '--arrowedgecolor', type=str, help='arrow outline color per arrow', nargs='+', default=None)
    parser.add_argument('-arrowlinestyle', '--arrowlinestyle', type=str, help='arrow shaft line style per arrow: - -- : -.', nargs='+', default=None)
    parser.add_argument('-arrowstyle', '--arrowstyle', type=str, help='arrow head/tail style per arrow: ->, -|>, fancy, simple, wedge', nargs='+', default=None)
    parser.add_argument('-arrowconnect', '--arrowconnect', type=str, help='arrow shaft routing style per arrow: arc3, arc, angle, or angle3', nargs='+', default=None)
    parser.add_argument('-arrowwidth', '--arrowwidth', type=str, help='arrow shaft line width per arrow in points', nargs='+', default=None)
    parser.add_argument('-arroworder', '--arroworder', type=str, help='z-order per arrow (higher value appears in front)', nargs='+', default=None)
    parser.add_argument('-polygon', '--polygon', type=str, help='polygon vertices as "x1a,x2a,x1b,x2b,..." in real coordinates', nargs='+', default=None)
    parser.add_argument('-polygonfacecolor', '--polygonfacecolor', type=str, help='fill color per polygon', nargs='+', default=None)
    parser.add_argument('-polygonedgecolor', '--polygonedgecolor', type=str, help='outline color per polygon', nargs='+', default=None)
    parser.add_argument('-polygonalpha', '--polygonalpha', type=str, help='transparency per polygon (0=transparent, 1=opaque)', nargs='+', default=None)
    parser.add_argument('-polygonlinestyle', '--polygonlinestyle', type=str, help='outline line style per polygon: - -- : -.', nargs='+', default=None)
    parser.add_argument('-polygonlinewidth', '--polygonlinewidth', type=str, help='outline line width per polygon in points', nargs='+', default=None)
    parser.add_argument('-polygonorder', '--polygonorder', type=str, help='z-order per polygon (higher value appears in front)', nargs='+', default=None)
    parser.add_argument('-circle', '--circle', type=str, help='circle specification as "x1center,x2center,radius" or "x1,x2,radius,rotation" in real coordinates', nargs='+', default=None)
    parser.add_argument('-circlefacecolor', '--circlefacecolor', type=str, help='fill color per circle', nargs='+', default=None)
    parser.add_argument('-circleedgecolor', '--circleedgecolor', type=str, help='outline color per circle', nargs='+', default=None)
    parser.add_argument('-circlealpha', '--circlealpha', type=str, help='transparency per circle (0=transparent, 1=opaque)', nargs='+', default=None)
    parser.add_argument('-circlelinestyle', '--circlelinestyle', type=str, help='outline line style per circle: - -- : -.', nargs='+', default=None)
    parser.add_argument('-circlelinewidth', '--circlelinewidth', type=str, help='outline line width per circle in points', nargs='+', default=None)
    parser.add_argument('-circleorder', '--circleorder', type=str, help='z-order per circle (higher value appears in front)', nargs='+', default=None)

    # graph
    if program in ['graph']:
        parser.add_argument('-close', '--close', type=strs2bool, help='close the curve by connecting the last point back to the first (y/n per curve)', default=None)
        parser.add_argument('-select', '--select', type=str, help='select specific column indices from the data (0-based), e.g. 0,2', nargs='+', default=None)
        parser.add_argument('-ftype', '--filetype', type=str, help='input file format: binary (default) or ascii', default='binary')
        parser.add_argument('-ptype', '--plottype', type=int, help='plot type: 1=y values only, 2=x,y pairs, 3=x,y,value scatter (default: 1)', default=1)
        parser.add_argument('-projection', '--projection', type=str, help='coordinate system: cartesian (default) or polar', default='cartesian')
        parser.add_argument('-linestyle', '--linestyle', type=str, help='line style per curve: - solid, -- dashed, : dotted, -. dash-dot, none (default: -)', nargs='+', default=None)
        parser.add_argument('-linewidth', '--linewidth', type=str, help='line width per curve in points', nargs='+', default=None)
        parser.add_argument('-linecolor', '--linecolor', type=str, help='line color per curve, e.g. k, r, blue, #ff0000', nargs='+', default=None)
        parser.add_argument('-linealpha', '--linealpha', type=str, help='line transparency per curve (0=transparent, 1=opaque)', nargs='+', default=None)
        parser.add_argument('-marker', '--marker', type=str, help='marker style per curve: o circle, s square, ^ triangle, + plus, x cross, none (default: none)', nargs='+', default=None)
        parser.add_argument('-markerevery', '--markerevery', type=str, help='place a marker every N-th data point per curve', nargs='+', default=None)
        parser.add_argument('-markersize', '--markersize', type=str, help='marker size per curve in points', nargs='+', default=None)
        parser.add_argument('-markerfacecolor', '--markerfacecolor', type=str, help='marker fill color per curve', nargs='+', default=None)
        parser.add_argument('-markeredgecolor', '--markeredgecolor', type=str, help='marker outline color per curve', nargs='+', default=None)
        parser.add_argument('-markeralpha', '--markeralpha', type=str, help='marker transparency per curve (0=transparent, 1=opaque)', nargs='+', default=None)
        parser.add_argument('-markersizemax', '--markersizemax', type=str, help='maximum marker size for value-scaled scatter plots (ptype=3)', nargs='+', default=None)
        parser.add_argument('-markersizemin', '--markersizemin', type=str, help='minimum marker size for value-scaled scatter plots (ptype=3)', nargs='+', default=None)
        parser.add_argument('-plotorder', '--plotorder', type=int, help='z-order for the data curves; higher value appears in front (default: 20)', default=20)
        parser.add_argument('-gridorder', '--gridorder', type=int, help='z-order for grid lines; higher value appears in front (default: 10)', default=10)
        parser.add_argument('-normalize1', '--normalize1', type=str, help='normalize data along axis 1: range (min-max), zscore, or a target numeric value', default=None)
        parser.add_argument('-normalize2', '--normalize2', type=str, help='normalize data along axis 2: range (min-max), zscore, or a target numeric value', default=None)

    # contour
    if program in ['contour', 'slicon', 'volcon']:
        parser.add_argument('-contours', '--contours', type=str, help='explicit contour levels as a comma-separated list, e.g. "0.1,0.5,1.0"; overrides contourbeg/end/level', nargs='+', default=None)
        parser.add_argument('-contourbeg', '--contourbeg', type=str, help='value of the first automatically-spaced major contour (auto if omitted)', default=None)
        parser.add_argument('-contourend', '--contourend', type=str, help='value of the last automatically-spaced major contour (auto if omitted)', default=None)
        parser.add_argument('-contourcolor', '--contourcolor', type=str, help='color(s) of major contour lines; single value or comma-separated list (default: k)', nargs='+', default='k')
        parser.add_argument('-contourwidth', '--contourwidth', type=str, help='line width of major contour lines in points (default: 1.0)', default='1.0')
        parser.add_argument('-contourstyle', '--contourstyle', type=str, help='line style of major contour lines: - -- : -. (default: -)', default='-')
        parser.add_argument('-contourlevel', '--contourlevel', type=str, help='interval between automatically-spaced major contours (auto if omitted)', default=None)
        parser.add_argument('-contourextend', '--contourextend', type=str, help='shade regions beyond outermost contours: neither, min, max, or both (default: both)', default='both')
        parser.add_argument('-contourevery', '--contourevery', type=int, help='draw every N-th major contour, e.g. 2 skips alternating contours (default: 1)', default=1)
        parser.add_argument('-clabelsize', '--clabelsize', type=str, help='font size of contour labels in points; set to 0 to hide labels (auto if omitted)', default=None)
        parser.add_argument('-clabelcolor', '--clabelcolor', type=str, help='color of contour labels (default: k)', default='k')
        parser.add_argument('-clabelbackcolor', '--clabelbackcolor', type=str, help='background fill color behind contour labels to improve readability', default=None)
        parser.add_argument('-mcontour', '--mcontour', type=int, help='number of minor contour lines drawn between consecutive major contours (default: 0)', default=0)
        parser.add_argument('-mcontourwidth', '--mcontourwidth', type=str, help='line width of minor contour lines in points (defaults to 0.25 × contourwidth)', default=None)
        parser.add_argument('-mcontourstyle', '--mcontourstyle', type=str, help='line style of minor contour lines: - -- : -. (default: -)', default='-')
        parser.add_argument('-contourfill', '--contourfill', type=str2bool, help='fill the regions between contours using the colormap (y/n)', default='n')

    # wiggle
    if program in ['wiggle']:
        parser.add_argument('-tracecolor', '--tracecolor', type=str, help='color of the zero-baseline trace lines', nargs='+', default=None)
        parser.add_argument('-wigglecolor', '--wigglecolor', type=str, help='fill colors for positive/negative wiggles, comma-separated per polarity (default: k,b,r,g,y,p,c)', nargs='+', default='k,b,r,g,y,p,c')
        parser.add_argument('-wigglewidth', '--wigglewidth', type=str, help='wiggle line width in points', nargs='+', default=None)
        parser.add_argument('-wigglestyle', '--wigglestyle', type=str, help='wiggle line style: - -- : -.', nargs='+', default=None)
        parser.add_argument('-axispad', '--axispad', type=str, help='fractional padding added to the axis range on each side (default: 0.1)', default='0.1')
        parser.add_argument('-interp1', '--interp1', type=str, help='upsample the data by this integer factor along axis 1 before plotting', default=None)
        parser.add_argument('-interp2', '--interp2', type=str, help='upsample the data by this integer factor along axis 2 before plotting', default=None)
        parser.add_argument('-along', '--along', type=int, help='axis along which wiggles are drawn: 1=rows (default) or 2=columns', default=1)
        parser.add_argument('-fill', '--fill', type=int, help='wiggle fill style: 0=none (default), 1=positive lobe, -1=negative lobe, 2=both lobes', default=0)
        parser.add_argument('-every', '--every', type=int, help='plot every N-th trace to reduce crowding (default: 1)', default=1)
        parser.add_argument('-wiggleloc', '--wiggleloc', type=str, help='ASCII file with one real-coordinate position per trace for irregularly spaced data', default=None)
        parser.add_argument('-wx1beg', '--wx1beg', type=str, help='axis-1 display range lower bound in real coordinates', default=None)
        parser.add_argument('-wx1end', '--wx1end', type=str, help='axis-1 display range upper bound in real coordinates', default=None)
        parser.add_argument('-wx2beg', '--wx2beg', type=str, help='axis-2 display range lower bound in real coordinates', default=None)
        parser.add_argument('-wx2end', '--wx2end', type=str, help='axis-2 display range upper bound in real coordinates', default=None)
    if program in ['wiggle', 'graph', 'contour', 'matrix']:
        parser.add_argument('-plotlabel', '--plotlabel', type=str, help='legend label text per curve/wiggle/image; omit to suppress the legend', nargs='+', default=None)
        parser.add_argument('-plotlabelloc', '--plotlabelloc', type=str, help='legend position: upper_right (default), upper_left, lower_right, or lower_left', default='upper_right')
        parser.add_argument('-plotlabelcol', '--plotlabelcol', type=int, help='number of columns in the legend box (default: 1)', default=1)
        parser.add_argument('-plotlabelsize', '--plotlabelsize', type=str, help='legend label font size in points (default: 14)', default='14.0')
        parser.add_argument('-fillwrt', '--fillwrt', type=str, help='fill between the curve and a reference line, e.g. y=0 or x=0', nargs='+', default=None)
        parser.add_argument('-fillcolor', '--fillcolor', type=str, help='fill color per curve when using fillwrt', nargs='+', default=None)
        parser.add_argument('-fillalpha', '--fillalpha', type=str, help='fill transparency per curve when using fillwrt (0=transparent, 1=opaque)', nargs='+', default=None)

    # misc
    parser.add_argument('-font', '--font', type=str, help='font family for all text elements, e.g. arial, times, helvetica (default: arial)', default='arial')
    parser.add_argument('-type3font', '--type3font', type=str2bool, help='embed Type-3 fonts in PDF/EPS output for full vector compatibility (y/n)', default='y')
    parser.add_argument('-tr', '--topright', type=str, help='path to an image file placed in the top-right corner; for slice plots only', default=None)
    parser.add_argument('-render', '--render', type=str, help='rendering backend for slice plots: 2d matplotlib (default) or 3d pyvista', default='2d')
    parser.add_argument('-camera', '--camera', type=str, help='3-D camera position as "x,y,z" in normalized scene coordinates (default: 1.5,1.5,1.5)', default='1.5,1.5,1.5')
    parser.add_argument('-size1', '--size1', type=str, help='plot height along axis 1 in inches; auto-scaled from data aspect ratio if omitted', default=None)
    parser.add_argument('-size2', '--size2', type=str, help='plot width along axis 2 in inches; auto-scaled from data aspect ratio if omitted', default=None)
    parser.add_argument('-size3', '--size3', type=str, help='plot size along axis 3 in inches; auto-scaled from data aspect ratio if omitted', default=None)
    parser.add_argument('-interp', '--interp', type=str, help='image resampling method: none, nearest, bilinear, bicubic, lanczos, etc. (default: none)', default='none')
    parser.add_argument('-backinterp', '--backinterp', type=str, help='resampling method for the background image (default: none)', default='none')
    parser.add_argument('-imageonly', '--imageonly', type=str2bool, help='output only the data area with no axes, ticks, or frame (y/n)', default='n')
    parser.add_argument('-direction', '--direction', type=str, help='arrangement of multi-panel figures: horizontal (default) or vertical', default='horizontal')
    parser.add_argument('-overlay', '--overlay', type=str2bool, help='draw contours or wiggles on top of the corresponding data image (y/n)', default='n')

    return parser
